apply_doc_patch_gh: "/usr/local/bin/gh"
apply_doc_patch_branch_name: "import-{{ doc_label }}-{{ zuul.change }}"
apply_doc_patch_pr_title: |
  Changes to {{ doc_label }} from doc-exports#{{ zuul.change }}
apply_doc_patch_pr_body_file: "{{ ansible_user_dir }}/{{ doc_label }}_pr_body.txt"
apply_doc_patch_pr_label: "autoPR"
apply_doc_patch_reject_file: "{{ ansible_user_dir }}/{{ doc_label }}_rej"
