---
- hosts: all
  tasks:
    - name: Read project docs configuration
      include_vars: "{{ docs_update_data_file }}"

    - name: Fetch generated artifacts
      include_role:
        name: "fetch_doc_artifacts"
      vars:
        fetch_doc_artifacts_name: "{{ doc.label }}"
        fetch_doc_artifacts_rst_source: "{{ ansible_user_dir }}/{{ docs_rst_location }}/{{ doc.label }}/{{ docs_new_location }}"
        fetch_doc_artifacts_diff_patch: "{{ ansible_user_dir }}/{{ doc.label }}.patch"
        fetch_doc_artifacts_git_patch: "{{ ansible_user_dir }}/{{ doc.label }}.git.patch"
      loop: "{{ docs }}"
      loop_control:
        loop_var: "doc"
        label: "{{ doc.label }}"
